ministryofjustice/hmpps-approved-premises-tools

bin/start-server, docker-compose.yml, tiltfile
Tilt was not working on my MBP - probably due to the emulation load the [community-api](https://github.com/ministryofjustice/community-api/) was putting on the machine.
Thanks to the work of @pezholio [here](https://github.com/ministryofjustice/community-api/pull/732) a multiplatform version of the community-api was created.
However the `ap-tools server start` script was still failing due to the dependencies between the services as mentioned in [this issue comment](https://github.com/tilt-dev/tilt/issues/2210#issuecomment-532957058). With these removed and with some patience whilst waiting for the community-api to come up, the issue is resolved.
=> Fix for ARM processors

bin/start-server
The Community API is the last thing that comes up when bringing the stack up. Before, we were just checking the port, which shows as up as soon as the container comes up. What we’re really interested in is if the HTTP server is up, so let’s poll the health endpoint instead.
=> Poll Community API health endpoint for readiness

wiremock/mappings/OffenderCaseNotes_GetCaseNotesForNomsNumber.json
We can't have a proper Offender Case Notes Service container because of issues with SQS so this adds a mock for the endpoint we need instead.
=> Add wiremock for offender case notes API

docker-compose.yml
Because Prison API is now using a replica datasource for certain read-only requests we need to point this at the persisted nomis-db directory too
=> Fix for Prison API docker container

wiremock/mappings/ApAndOAsys_GetRiskManagementPlan.json, wiremock/mappings/ApAndOasys_GetOffenceAnalysis.json, wiremock/mappings/ApAndOasys_GetRiskContributors.json, wiremock/mappings/ApAndOasys_GetRoshSummary.json
This is the first in several OASys endpoint stubs which are needed to enable our UI work to progress whilst we wait for the upstream APIs to come online.
These stubbed endpoints will be called at the new `approved-premises-and-oasys` API being built by integrations as a facade over the (also) new Oracle ORDS endpoints being built by the Capita team. e.g.
```
GET https://approved-premises-and-oasys-dev.hmpps.service.justice.gov.uk/offence-details/{crn}
```
See https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/216 for our initial design for how these responses will be enhanced by our API to make them clearer for implementation at the UI.
=> Wiremock stubs for AP-to-OASys API

wiremock/mappings/ApAndOasys_GetRisksToOthers.json
This is confusingly exposed by OASys and the AP-and-OASys APIs as:
`/risk-assessment/{crn}`
The human readable labels in our AP service's API:
R6.1 FA1: Current offence details
R6.1 FA2: Current where and when
R6.1 FA3: Current how
R6.1 FA4: Current who
R6.1 FA5: Current others present
R6.1 FA6: Current why
R6.1 FA7: Current sources
R6.2 FA8: Previous offence details
R6.2 FA9: Previous where and when
R6.2 FA10: Previous how
R6.2 FA11: Previous who
R6.2 FA12: Previous others present
R6.2 FA13: Previous why
R6.2 FA14: Previous sources
=> Add wiremock stub for OASys risks to others (R6.1, R6.2)

wiremock/mappings/ApAndOasys_GetRoshRiskRatings.json
The data from this endpoint is used to build the risk widget we show in the sidebar.
We've been getting these ratings from ARN (`/risks/crn/$crn`) in the ARN client's `getRoshRisks` function via the `OffenderService`
https://github.com/ministryofjustice/approved-premises-api/blob/f089b31a34e4bf734657f16491f6207a57dbeb38/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/service/OffenderService.kt#L277-L292
So that we are sure to be using data from the same OASys assessment throughout the AP service we need to refactor this code to use the new `ap-and-aoays/rosh` endpoint which provides these ratings from the latest layer 3 assessment regardless of its status -- rather from the latest *complete* assessment, as is the case with ARN.
=> Add wiremock for new RoSH risk ratings (R10.6) endpoint

wiremock/mappings/ApAndOasys_GetOffenceAnalysis.json
The payload property in the wrapper is named `offence` rather than `offenceDetails`
=> Correct offence-analysis wiremock mapping

docker-compose.yml, wiremock/mappings/ApDeliusContext_CheckManagingTeam.json
JimSnowLdap is a member of team `A00IAV` so the stub is configured to return that team as the managing team for all CRNs.  The URL for AP Delius Context API was also missing so that is now pointed at Wiremock.
=> Add stub for AP Delius Context Managing Teams endpoint

.gitignore, Brewfile, README.md, bin/server, bin/start-server, bin/utils/install-dependencies.sh, bin/utils/refresh-containers.sh
This will allow us to pull all the containers, delete the local databases, and start from scratch.
To make this a bit more robust, I’m using `yq` to fetch all the containers defined in the docker-compose file. With this in mind, I’ve added a Brewfile to automatically install the dependencies if the user has Homebrew installed.
=> Add a refresh flag

docker-compose.yml, tiltfile
The API now uses localstack to mock SQS in dev, so we need to add it to our containers or the API won't spin up
=> Add localstack to the setup

docker-compose.yml
When the API is running in a container it needs to point Localstack traffic to the localstack container's host name instead of localhost
=> Point API at correct Localstack URL

docker-compose.yml
- Our environments are currently running version 4.x.x
- We've been asked to upgrade due to EOL
- I can't find out why we are using bitnami rather than the official redis image, to avoid potential problems with the upgrade I'm going to keep the surface area of problems smaller by staying with the same maintainer - one for later
- apparently redis supports backwards compatibility even between major changes[1] so we should be able to attempt the otherwise big jump in one go
[1] https://user-guide.cloud-platform.service.justice.gov.uk/documentation/deploying-an-app/redis/upgrade.html#upgrade-paths
=> Upgrade to Redis 7.0.11

docker-compose.yml
Since https://github.com/ministryofjustice/prison-api/commit/cc4390bba61c7e823ba76fd837a9ffdd35487b8c the jwks is fetched from HMPPS Auth, rather than a local file. As we run HMPPS Auth on a different port, we need to set an environment var, so Prison API looks in the right place.
=> Add JWKS URI to Prison API config

wiremock/mappings/ApDeliusContext_GetStaff.json
We need to use a Staff code that we know exists in the Community API dev container, otherwise we can’t record arrivals locally, as Community API 404s when trying to get the user when creating an arrival.
=> Use a code that exists in Community API for stubs

docker-compose.yml
Failing to start because of failure to create directory - using tmp instead of the default works
=> Fix for API failing to start

docker-compose.yml, wiremock/mappings/AdjudicationsApi_GetAdjudicationsPage.json
This allows ap-tools to handle requests from the Approved Premises API to the Adjudications API, enabling the change in
https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/892/ to function within the ap-tools stack.
=> Add Wiremock integration for Adjudications API

README.md, docker-compose.yml, tiltfile
CAS2 users are Prison Offender Managers (POMs) and so need
to authenticate with our service using their NOMIS credentials.
The [NOMIS User Roles API](https://github.com/ministryofjustice/nomis-user-roles-api)
project provides a mechanism to authenticate using a local
store of NOMIS users.
See https://github.com/ministryofjustice/nomis-user-roles-api/blob/main/src/main/resources/db/dev/V3_1__user_data.sql
for a list of available credentials.
We can now log in with either Delius creds (`JimSnowLdap`) or
NOMIS creds (e.g. `POM_USER`).
=> Authenticate with NOMIS creds (as well as via Delius)

wiremock/mappings/ApAndOasys_GetRoshRiskRatings.json
This mock was failing locally because we were using the text rather than
the value of the enum. The CAS API was not able to deserialise the
values and threw this error:
```
com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot
deserialize value of type
`uk.gov.justice.digital.hmpps.approvedpremisesapi.model.oasyscontext.RiskLevel`
from String "Medium": not one of the values accepted for
Enum class: [HIGH, VERY_HIGH, LOW, MEDIUM]
```
From looking at where it's returned by oasys integration API here:
https://github.com/ministryofjustice/hmpps-probation-integration-services/blob/b9f45438382167bb353e00790a5cc130938ab09f/projects/approved-premises-and-oasys/src/main/kotlin/uk/gov/justice/digital/hmpps/model/RoshDetails.kt#L64
There is a `fromString` method that converts the text …
=> fix: use uppercase values for rosh risk ratings

docker-compose.yml, wiremock/mappings/ApDeliusContext_GetCaseDetail.json, wiremock/mappings/HmppsAuthAndDelius_Authenticate.json, wiremock/mappings/HmppsAuthAndDelius_GetUser.json
This adds a new mock for a new Approved Premises and Delius endpoint, as well as fixes not being able to log in via HMPPS Auth, as the latest version of Auth now points to a custom integration, rather than Community API.
=> Add new mocks

README.md, bin/start-server, seed/hmpps-auth/V901_2__groups_roles.sql, seed/hmpps-auth/V901_3__users.sql
We can now log in locally as an external NACRO user.
username: `CAS2_ASSESSOR_USER`
password: `password123456`
The important `claims` keys of the issued JWT will look like:
```json
{ "user_name": "CAS2_ASSESSOR_USER",
"auth_source": "auth",
"authorities": [
"ROLE_CAS2_ASSESSOR"
],
}
```
This can be referenced with either `hasRole("CAS2_ASSESSOR")` or `hasAuthority("ROLE_CAS2_ASSESSOR")` in Spring Security filters
=> Add seeding for external CAS2_ASSESSOR_USER

bin/ap-tools, bin/start-server, bin/utils/check-for-update.sh
This provides a convenience functionality to ap-tools so that upstream changes are propagated to users without manual intervention, minimising errors due to outdated integrations.
Updates will occur when:
1. The current ap-tools branch is `main` (to avoid trampling over any potential changes in-flight)
2. The upstream version of `main` is different to the local version
3. The upstream version can be successfully `git pull`ed
If an update occurs, this will also automatically trigger a container refresh (as if the `--refresh` flag had been specified).
Automatic updates can be prevented by using the `--no-update` flag.
=> Add auto-update functionality to ap-tools command

wiremock/mappings/ApDeliusContext_GetUserAccess.json
The Approved Premises API calls the `/users/access` endpoint from the Delius Integration API to get authorisation for personal details in bulk. However, the Wiremock mapping to mimic this functionality is incorrectly mapping `/user/access`.
=> Use correct endpoint for ApDeliusContext_GetUserAccess.json

docker-compose.yml, wiremock/mappings/ProbationOffenderSearchApi_SearchByNomsNumber.json
We need to allow a CAS2 user to search for an offender by prison nubmber (`nomsNumber`). This adds a mocked response from the `probation-offender-search` API for searches using Aadland Bertland's `nomsNumber`. I think the shape of the data returned should match a prisoner detail from the probation API, which is a list of `OffenderDetails`.
See their controller tests:
https://github.com/ministryofjustice/probation-offender-search/blob/7093fdf716f969de3b80827675f8389cef01f95c/src/test/kotlin/uk/gov/justice/hmpps/probationsearch/controllers/OffenderSearchControllerTest.kt
And test fixtures:
https://github.com/ministryofjustice/probation-offender-search/blob/a6add4b33fd2aca9928da2cdd4bd276a101dd8b3/src/test/resources/searchdata/james-brown.json
But I haven't been able to see a 'real' response …
=> Mock response from `probation-offender-search`

seed/hmpps-auth/V901_3__users.sql
This is to avoid seeing a reminder form to add an email, and ensures our local setup matches test users set up in dev.
=> Add email for CAS2 admin

docker-compose.yml, tiltfile
This change ensures that approved-premises-and-delius is running before the CAS API starts. This is to ensure that the approved-premises-and-delius endpoint is available if/when a CAS1 autostart scripts runs to automatically create applications.
=> APS-768 CAS API depends on approved-premises-and-delius

bin/start-server, wiremock/mappings/ApAndOasys_GetOffenceAnalysis.json, wiremock/mappings/ApAndOasys_GetRisksToTheIndividual.json, wiremock/mappings/noms_number_A5671YZ/ApAndOasys_GetOffenceAnalysis.json, wiremock/mappings/noms_number_A5671YZ/ApAndOasys_GetRisksToTheIndividual.json, wiremock/mappings/noms_number_A5671YZ/ProbationOffenderSearchApi_SearchByNomsNumber.json
CAS2 want to write a new E2E test to cover the case where an OASYS record exists but is older than 6 months, in which case the stack returns a 404 instead. We know this happens often enough and so we believe it warrants test coverage.
- The CAS2 FE asks the API for an oasys record via `/cas2/people/X320741/oasys/risk-to-self`. [This people controller will then make two requests for oasys data](https://github.com/ministryofjustice/hmpps-approved-premises-api/blob/7128dba72aeb13c6f72a1f7a678671d869f12350/src/main/kotlin/uk/gov/justice/digital/hmpps/approvedpremisesapi/controller/cas2/PeopleController.kt#L51) and those requests will we now stub out with 404s with our new mocks. There are lots of other mocks we _could_ write, visible by other mapping files, but we with this we are able to …
=> Start mocking requests for NOMS number A5671YZ

bin/server, bin/start-server, bin/utils/install-or-update-intergration-services.sh
This commit also changes the probation-integration clone to use https instead of ssh as this is more widely supported
=> APS-768 Fail server start if errors occur

bin/start-server, seed/nomis-user-roles/V3_2__user_data.sql, wiremock/mappings/noms_number_A1234AJ/ApAndOasys_GetOffenceAnalysis.json, wiremock/mappings/noms_number_A1234AJ/ApAndOasys_GetRisksToTheIndividual.json, wiremock/mappings/noms_number_A1234AJ/ProbationOffenderSearchApi_SearchByNomsNumber.json
This PR makes two changes to ensure our users will be able to make applications for offenders in their prison.
1. changes the secondary offender's nomsNumber - from [Prison API seeded data here,](https://github.com/ministryofjustice/prison-api/blob/37b7392bc69960f159de27e72aee19a9ae7e6ad5/src/main/resources/db/migration/data/R__1_15__OFFENDERS.sql#L26) retaining the old path temporarily until we have updated the UI e2e tests.
2. changes the active agency ID of our local users to match our local offenders
For CAS2, we make three main requests for prison data
* Probation Offender Search - called with `nomsNumber` - locally, this is entirely stubbed in wiremock in this tools repo
* Prison API - called with `nomsNumber` - locally, we talk to the `prison-api` container, so we rely on [data …
=> CAS2-465: update local prison data

.gitignore, README.md, bin/start-server, bin/utils/install-dependencies.sh, bin/utils/launch-docker.sh, tiltfile
This commit refreshes the README to better reflect how the tools are typically used and provide instructions in a logical order.
This commit refreshes the README to better reflect how the tools are typically used and provide instructions in a logical order.
It also renames some env vars to reflect that they’re used for all CASs:
APPROVED_PREMISES_API_PATH becomes LOCAL_CAS_API_PATH
APPROVED_PREMISES_UI_PATH becomes LOCAL_CAS_UI_PATH
=> Improve README & rename APPROVED_PREMISES_API_PATH

wiremock/mappings/ApAndOasys_GetRoshRiskRatings.json, wiremock/mappings/ApDeliusContext_GetCaseDetail.json, wiremock/mappings/AssessmentApi_GetLatestCompletedAssessmentRoshSectionAnswers.json, wiremock/mappings/ProbationOffenderSearchApi_SearchByNomsNumber.json, wiremock/mappings/noms_number_A1234AJ/ApAndOasys_GetOffenceAnalysis.json, wiremock/mappings/noms_number_A1234AJ/ApAndOasys_GetRisksToTheIndividual.json, wiremock/mappings/noms_number_A1234AJ/ProbationOffenderSearchApi_SearchByNomsNumber.json, wiremock/mappings/noms_number_A5671YZ/ApAndOasys_GetOffenceAnalysis.json, wiremock/mappings/noms_number_A5671YZ/ApAndOasys_GetRisksToTheIndividual.json, wiremock/mappings/noms_number_A5671YZ/ProbationOffenderSearchApi_SearchByNomsNumber.json
We’ve started seeing the error “ID of the provided stub mapping '3e862519-78b0-4449-b2b5-535ee1b81213' is already taken by another stub mapping”. This commit makes all stub mapping IDs unique. I suspect we can just remove these IDs, but I wanted to minimise change with the aim of unblocking this issue
=> Make wiremock stub mapping IDs unique

seed/community-api/V99_3__regions_and_staff.sql, wiremock/mappings/HmppsAuthAndDelius_GetUser_SheilaHancockNPS.json
We use the existing [SheilaHancockNPS user][] defined in CommunityAPI's LDAP seeding.
And we [adjust the staff entry][] which corresponds to this user to set a probation area and set a name of 'E2E CRU Member'.
[SheilaHancockNPS user]:
https://github.com/ministryofjustice/community-api/blob/736ac63ff7705a0c8d998ed2773d59563b0fdea4/src/main/resources/schema.ldif#L137C1-L148C21
[adjust the staff entry]:
https://github.com/ministryofjustice/community-api/blob/736ac63ff7705a0c8d998ed2773d59563b0fdea4/src/main/resources/db/data/V1_4__offenders_licences_data.sql#L12C1-L15C1
See also related PRs:
- UI: https://github.com/ministryofjustice/hmpps-approved-premises-ui/pull/1902
- API: https://github.com/ministryofjustice/hmpps-approved-premises-api/pull/1978
=> CAS1 Seeding: add Delius user for CAS1 'CRU Member' persona

README.md
docker-compose is the v1 docker compose command which is now deprecated/removed. We should use `docker compose` instead
=> Update README to use `docker compose`

docker-compose.yml, tiltfile
Previously (a long time ago) we used to retrieve the risk ratings used to 
build the sidebar widget from ARN.
To avoid the possibility of having mismatched
risk information from both OASys and ARNs we
switched to obtaining the risk ratings from
OASys. See: 
`wiremock/mappings/ApAndOasys_GetRoshRiskRatings.json`
=> Remove Assess-Risks-And-Needs: unused

docker-compose.yml
This is in line with work to upgrade localstack in API from 1.3.1 to 3.4.0.
=> CAS-365 Upgrade localstack version from 1.3.1 to 3.4.0.

docker-compose.yml
The fully featured health check we were previously using on http://localhost:8096/health fails because we don’t have an instance of the delius api deployed locally (nor do we need one).
To avoid this service appearing in an unhealth state in tilt, this commit changes to the use simpler and more shallow health check available on http://localhost:8096/health/ping
=> Change hmpps-manage-users-api healthcheck

.gitignore, README.md, bin/server, bin/start-server, bin/stop-server, bin/utils/clear-databases.sh, docker-compose.yml, tiltfile
This commit moves all database files into a top-level 'databases' folder. It also adds a 'clear-databases' option when stopping ap-tools to clear all databases, including the API database. This simplifies database management and removes the need to run an additional delete volumes command to clear databases.
This commit also improves the health check when starting ap-tools to use the API healthcheck endpoint instead of community api.
=> APS-1292 - Move DBs into one folder, simplifying clear down

bin/start-server, bin/stop-server, bin/utils/clear-databases.sh, docker-compose.yml, tiltfile
Docker performance when writing to a mapped folder is proving to be poor when used for postgres (e.g. over 1 minute to start from scratch vs 10 seconds if using a docker managed volume).
This coupled with the fact that when using --local-api tilt will only check if postgres is running (not ready) before starting the API is leading to start ups failing
This commit looks to provide stability by:
* Using a docker managed volume for postgres data (as was the case before the previous commit that instead mapped the data to ‘databases/api’
* Update —clear-databases option on stop to also delete docker managed volumes
* Show STDERR messages when starting tilt
* Add a pause between tilt stopping and clearing databases (if required) to ensure that probation-integration has enough time to unlock its …
=> Use docker volume for postgres

bin/utils/refresh-containers.sh, docker-compose.yml
nomis-db is technically correct, but prison-api more user friendly when trying to figure out which database to clear for prison-api
=> Rename ‘nomis-db’ folder to ‘prison-api’

.env.local.api-docker, .env.local.api-gradle, docker-compose.yml, tiltfile, wiremock/mappings/HmppsAuthAndDelius_GetUser_AP_USER_TEST_1.json, wiremock/mappings/HmppsAuthAndDelius_GetUser_AP_USER_TEST_2.json, wiremock/mappings/HmppsAuthAndDelius_GetUser_AP_USER_TEST_3.json, wiremock/mappings/HmppsAuthAndDelius_GetUser_AP_USER_TEST_4.json, wiremock/mappings/HmppsAuthAndDelius_GetUser_AP_USER_TEST_5.json, wiremock/mappings/HmppsAuthAndDelius_GetUser_TEMPORARY-ACCOMMODATION-TRAINING-1.json, wiremock/mappings/HmppsAuthAndDelius_GetUser_TEMPORARY-ACCOMMODATION-TRAINING-2.json
Before this commit we were relying on default config in the api projects application-local.yml to configure various connections details. This commit copies that config into the locally managed API config to give a more comprehensive view of the configuration being used. In time we should remove this duplication from application-local.yml
Furthermore, this commit adds some additional configuration that we’ll need to change/override if testing to upstream dev services for end to end testing
This commit also adds auth configuration for CAS1/3 dev e2e test users
=> Make api config comprehensive & add test users

wiremock/mappings/ApAndOasys_GetNeedsDetails_Default.json, wiremock/mappings/ApAndOasys_GetNeedsDetails_S517283.json, wiremock/mappings/HMPPSTier_GetTierForCrn_Default.json, wiremock/mappings/HMPPSTier_GetTierForCrn_S517283.json
The crn S517283 was recently added to support local testing of the Women’s Estate functionality
This commit adds specific wiremocks for this CRN for the following:
* ApAndOasys_GetNeedsDetails -> Ensures all available checkboxes are shown, arranged under different sections compared to the default configuration
* HMPPSTier_GetTierForCrn -> Returns tier ‘A1’, meaning it’s not an exceptional case. The default tier of ‘D2’ triggers the exception case flow on the UI
=> Add specific OAsys and Tier response for new CRN

docker-compose.yml
hmpps-external-users-api has recently switched to using the hmpps-sqs lbrary to connect to SQS
This commit adds the configuration required for the tool to use our localstack deployemnt (config was taken from the CAS API equivalent)
=> Fix hmpps-external-users-api localstack config

docker-compose.yml
We’re currently having some issues with the hmpps-external-users-api flyway scripts being out of sync with the hmpps-auth flyway scripts. As they share a database this is causing problems on startup. This commit introduces a separate database for hmpps-external-users-api until this problem is resolved. This should be fine because we only read from this database and make use of the seeded test users
=> Add auth db for external users

docker-compose.yml
M4 chip 15.2 cannot use 21.0.5 java in docker containers, this is a workaround until the fix comes in at 21.0.7
=> Add java tool options config for M4 chip

docker-compose.yml
The previous commit introduced custom seed migrations for hmpps-external-users-api, but in the process set incorrect internal migration paths
=> Fix hmpps-external-users-api db migration config

README.md, bin/ap-tools, bin/start-server, tiltfile
Enables two UIs to be run at once. 🙀 
With more work happening between CAS2 and 3 UIs, there has been a lot of context switching, and having to turn on an off your environments to switch them over is a right faff!
To get this working make sure you add the path to your zschr file
`export SECOND_LOCAL_CAS_UI_PATH=/Users/your-directories/hmpps-temporary-accommodation-ui`
I have this working locally for me, but I haven't used it in anger - so it would be grand if someone else could give this a go before being merged
=> Enable two UIs to be run at once!

docker-compose.yml
We use a postgis docker image becuase this has the postgis extensions pre-installed (much like, RDS). The ‘vanilla’ postgres image does not have postgis extensions pre-installed.
=> Align postgres version with production

wiremock/mappings/noms_number_A1234AJ/ProbationOffenderSearchApi_SearchByNomsNumber.json
In CAS2 we were seeing some weird behaviour when a POM tried to create an application for Limited Access Offender(LAO). When they started the application and entered in `A1234AJ` it would show them all the offenders details but on the "Confirm details" page where the POM actually starts the new application it would reject them and say they dont have permission.
This odd behvious was only been seen in local development. This was because the first lookup for A1234AJ was using this wiremock mock and the second one to start the actual new application was using the probation integration services and the two services were not in sync.
see
https://github.com/ministryofjustice/hmpps-probation-integration-services/blob/524e676f89c2ef7140ea5e21e7e88b85678071bb/projects/approved-premises-and-delius/s …
=> Sync NOMS offender A1234AJ with HMPPS Probation Integration Services.

wiremock/mappings/ProbationOffenderSearchApi_SearchByNomsNumber_A5276DZ_Cas2v2.json
I let a a wiremock slip through with a duplicate uuid, this PR fixes that.
=> fix: duplicate wiremock uuid

bin/stop-server
This change will ignore any error returned by the `killall tilt` command, which errors if there are no instances of tilt running.
This ensures that even if tilt isn’t running when the `stop` command is issued, we still clear any database volumes managed by compose.
=> Clear database on stop even if tilt not running

docker-compose.yml
This allows us to see all requests and responses being proxied
=> Enable verbose wiremock logging

.env.api.template, .env.ui.template, bin/utils/resolve_secrets.sh
Add any configuration defined in the API local.yml into the api.template, and document the purpose of these files.
This includes an update to `resolve_secrets.sh` to remove any lines starting with a # when processing a template. This avoids issues when trying to `export` the template values as ENV VARS for npm
=> Revise API config and document the templates

.env.api.template
This commit updates the `env.api.template` to use the `localdev` spring profile, and removes any configuration that is managed by that profile.
=> Use localdev profile for API

.gitignore, docker-compose.yml
There is not a native docker image available for postgis. Where as docker would previously download and use a different platform if there is no local image provided (regardless of platform), this is no longer the case. Therefore, we explicitly specify which platform to use for postgis
i’ve also added `.env.ui` to the .gitignore to avoid accidental checkins when switching from the firebreak ap tools branch
=> Specify postgres platform

docker-compose.yml, tiltfile
Without these dependencies when starting on a fresh machine (without docker images) the API is likely to fail on startup
=> Improve startup dependencies

.env.cas1-ui.template, .env.cas2-ui.template, .env.cas3-ui.template, .gitignore, README.md, SETUP.md, bin/start-server, bin/stop-server, bin/utils/override_ui_props_with_local_ui_props.sh, bin/utils/resolve_secrets.sh, docker-compose.yml, tiltfile
Before this change when running a UI via docker the corresponding code must still be checked out and the `.env` file bootstrapped.
This commit fixes that issue by introducing a separate `.env.ui` file for each user interface, and adding a mandatory command line argument to indicate which UI is being used e.g.
```ap-tools server start --cas1```
This also fixed a bug that meant we weren’t actually stopping locally running UIs when running `ap-tools stop`. This is because we force killed the tilt process (`using killall -9`)
=> Remove need for checked out bootstraped ui code

wiremock/README.md, wiremock/mappings/overrides/README.md, wiremock/mappings/overrides/ap-and-oasys-needs-details.json, wiremock/mappings/overrides/ap-and-oasys-offence-details.json, wiremock/mappings/overrides/ap-and-oasys-risk-management-plan.json, wiremock/mappings/overrides/ap-and-oasys-risk-to-the-individual.json, wiremock/mappings/overrides/ap-and-oasys-rosh-summary.json, wiremock/mappings/overrides/hmpps-tier_get-tier-for-crn.json
This commit adds some wiremock override files that can be optionally enabled to manually test oasys integration.
The content of these files are identical to those previously in the project because we started using upstream dev ap-and-oasys services, with some improvements to fake names
=> Add optional oasys overrides

Brewfile
The scripts now require the `op` command to run, it's not in the brew file.
=> fix: added 1passwd to the brew file
